#!/bin/bash

#                         __ _ _      
#  __  ___ __  _ __ ___  / _(_) | ___ 
#  \ \/ / '_ \| '__/ _ \| |_| | |/ _ \
# _ >  <| |_) | | | (_) |  _| | |  __/
#(_)_/\_\ .__/|_|  \___/|_| |_|_|\___|
#       |_|                           
#

userresources="$XDG_CONFIG_HOME"/X11/Xresources
sysresources=/etc/X11/xinit/.Xresources

# merge in defaults and keymaps
if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

# start default X11 stuff
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# set bitwarden session key
if [ -f "$HOME/.config/bw-unlock.sh" ]; then
  source "$HOME/.config/bw-unlock.sh"
fi

# setup custom screen setup
if [ -f $HOME/.config/default-screen-setup ]; then
  $HOME/.config/default-screen-setup
fi

# setup graphics part of window manager
picom -b --config $HOME/.config/picom/picom.conf
set-wallpaper &

# start simple X hotkey daemon
sxhkd &

# start lockscreen
xss-lock -- $HOME/bin/lock-screen &

# set default cursor to arrow
xsetroot -cursor_name left_ptr

# disable pointing stick on laptop
xinput disable "DualPoint Stick"

# applets
nm-applet &
dunst &
udiskie &

# auto-reload X11 resources
( cd $HOME/.config/X11; ls Xresources | entr xrdb Xresources & )

