#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Google-chrome desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a Code desktop='^3'
bspc rule -a Subl3 desktop='^3'
bspc rule -a Org.gnome.Nautilus desktop='^4'
bspc rule -a Thunar desktop='^4'
bspc rule -a Pcmanfm desktop='^4'
bspc rule -a Spotify desktop='^5'
bspc rule -a vlc desktop='^5'
bspc rule -a Slack desktop='^6'
#bspc rule -a Gimp desktop='^8' state=floating follow=on
