[manager]
linemode = "size"

[opener]
show = [
  { run = 'sxiv "$1"', desc = "Show", for = "linux" },
]

[open]
prepend_rules = [
  { mime = "video/*", use = ["play", "reveal"] },
  { name = "*.3gp", use = ["play", "reveal"] },
  { name = "*.3g2", use = ["play", "reveal"] },
  { name = "*.avchd", use = ["play", "reveal"] },
  { name = "*.avi", use = ["play", "reveal"] },
  { name = "*.f4v", use = ["play", "reveal"] },
  { name = "*.flv", use = ["play", "reveal"] },
  { name = "*.m4v", use = ["play", "reveal"] },
  { name = "*.mkv", use = ["play", "reveal"] },
  { name = "*.mov", use = ["play", "reveal"] },
  { name = "*.mp4", use = ["play", "reveal"] },
  { name = "*.mpeg", use = ["play", "reveal"] },
  { name = "*.ogv", use = ["play", "reveal"] },
  { name = "*.ts", use = ["play", "reveal"] },
  { name = "*.webm", use = ["play", "reveal"] },
  { name = "*.wmv", use = ["play", "reveal"] },

  { mime = "image/*", use = ["show", "reveal"] },
  { name = "*.gif", use = ["show", "reveal"] },
  { name = "*.jpeg", use = ["show", "reveal"] },
  { name = "*.jpg", use = ["show", "reveal"] },
  { name = "*.png", use = ["show", "reveal"] },
  { name = "*.svg", use = ["show", "reveal"] },
  { name = "*.webp", use = ["show", "reveal"] },
]



