[open]
rules = [
	{ name = "*.mov", use = "play" },
	{ name = "*.MOV", use = "play" },

	{ name = "*.mp4", use = "play" },
	{ name = "*.MP4", use = "play" },

	{ name = "*.ts", use = "play" },
	{ name = "*.TS", use = "play" },

	{ name = "*.wmv", use = "play" },
	{ name = "*.WMV", use = "play" },

	{ name = "*.webm", use = "play" },
	{ name = "*.WEBM", use = "play" },
]
