[manager]
linemode = "size"

[open]
rules = [
	{ name = "*.avi", use = "play" },
	{ name = "*.AVI", use = "play" },

	{ name = "*.mov", use = "play" },
	{ name = "*.MOV", use = "play" },

	{ name = "*.m4v", use = "play" },
	{ name = "*.M4V", use = "play" },

	{ name = "*.mp4", use = "play" },
	{ name = "*.MP4", use = "play" },

	{ name = "*.ts", use = "play" },
	{ name = "*.TS", use = "play" },

	{ name = "*.wmv", use = "play" },
	{ name = "*.WMV", use = "play" },

	{ name = "*.webm", use = "play" },
	{ name = "*.WEBM", use = "play" },
]
