#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "Top CPU consumers" "$(ps axh -o comm:30,%cpu --sort=-%cpu | sed 's/$/%/' | head)" ;;
	2) notify-send "CPU module " "\- Shows CPU temperature.
- Click to show intensive processes.
- % is of single core." ;;
esac

sensors | awk '/Core 0/ {print $3}'
